# Generated by Django 3.2.6 on 2021-08-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobee',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
